import type { DocPage, DocSection } from "./types";

function advanced(slug: string, title: string, description: string, sections: DocSection[]): DocPage {
  return { slug: `advanced/${slug}`, title, description, eyebrow: "Advanced", sections };
}

export const additionalAdvancedPages: DocPage[] = [
  advanced("schema", "MemoGrafter schema", "Understand the generated mg-schema.ts reference, the PostgreSQL objects it describes, and the boundary between MemoGrafter and application data.", [
    {
      title: "Generated schema reference",
      body: [
        "`npx memo-grafter init` creates `src/memo-grafter/mg-schema.ts`. It is an auto-generated, read-only reference for the PostgreSQL extensions, tables, columns, constraints, and indexes required by the installed MemoGrafter version.",
        "Do not edit this file manually. Re-run `npx memo-grafter init` after upgrading MemoGrafter to regenerate it, review the resulting diff, and commit it with your project.",
      ],
      code: [{
        label: "terminal",
        language: "bash",
        code: `npx memo-grafter init
npx memo-grafter migrate
npx memo-grafter doctor`,
      }],
    },
    {
      title: "Reference versus migration",
      bullets: [
        "`mg-schema.ts` describes the schema; importing the file does not create database objects.",
        "`npx memo-grafter migrate` enables the required extensions and creates or updates MemoGrafter-owned database infrastructure.",
        "`npx memo-grafter doctor` checks extensions, migration state, and required core tables without changing the database.",
        "MemoGrafter migrations manage only MemoGrafter-owned objects. Keep application tables in your existing Prisma, Drizzle, SQL, or custom migration workflow.",
      ],
    },
    {
      title: "Required PostgreSQL extensions",
      bullets: [
        "`vector` provides pgvector columns and similarity indexes for topic and memory embeddings.",
        "`pgcrypto` provides UUID generation for memory, edge, and graft-registry rows.",
      ],
    },
    {
      title: "Conversation and ingestion tables",
      bullets: [
        "`mg_sessions` stores human-friendly session labels, descriptions, tags, and timestamps.",
        "`mg_message_buffer` stores ordered raw user and assistant messages for each session.",
        "`mg_segments` records the message ranges, topic order, and drift score of detected topic segments.",
        "`mg_session_ingest_state` stores the last successfully ingested message index so incremental ingestion can resume safely.",
      ],
    },
    {
      title: "Topic graph tables",
      bullets: [
        "`mg_topic_nodes` stores topic summaries, embeddings, tags, provenance, ordering, fleet ownership, and suppression state.",
        "`mg_topic_edges` connects topic nodes with temporal, semantic, reentry, and graft relationships plus their weights.",
      ],
    },
    {
      title: "Structured memory tables",
      bullets: [
        "`mg_memory_nodes` stores atomic facts, insights, questions, tasks, and references with embeddings, structured quality, provenance, tags, and lifecycle state.",
        "`mg_memory_edges` stores semantic, conflict, update, and related relationships between memory nodes.",
        "Lifecycle columns retain forgotten, decayed, superseded, conflict, and suppression information so normal recall can filter inactive memory while history remains inspectable.",
      ],
    },
    {
      title: "Grafting and fleet tables",
      bullets: [
        "`mg_graft_registry` records the source session and source topic for copied topic nodes, preserving graft provenance.",
        "`mg_fleets` stores metadata for multi-agent memory groups.",
        "`mg_fleet_agents` registers worker agents, their sessions, and their unique color within a fleet.",
      ],
    },
    {
      title: "Indexes and constraints",
      body: [
        "The generated schema also lists the indexes and constraints used for session ordering, lifecycle filtering, tags, fleet lookup, graft ownership, and vector similarity search.",
      ],
      bullets: [
        "Vector indexes accelerate similarity search over `mg_topic_nodes.embedding` and `mg_memory_nodes.embedding`.",
        "Lifecycle indexes support active-topic and active-memory filtering.",
        "Tag indexes support scoped topic and memory lookup.",
        "Foreign keys connect segments, topic nodes, memory nodes, edges, fleets, and graft records.",
        "Unique constraints prevent duplicate segments, duplicate topic ownership, fleet color collisions, and duplicate graft-registry ownership.",
      ],
    },
    {
      title: "Operational guidance",
      bullets: [
        "Treat every `mg_*` table as MemoGrafter-owned infrastructure.",
        "Use supported APIs and lifecycle operations instead of directly mutating graph or memory rows.",
        "Back up MemoGrafter tables according to the same recovery policy as the application data that depends on them.",
        "Run migration as an intentional installation, upgrade, or deployment step rather than on every application request.",
        "Review regenerated schema changes before deploying a new MemoGrafter version.",
      ],
    },
    {
      title: "Related documentation",
      links: [
        { label: "Installation", href: "/docs/installation", description: "Generate the project files, migrate the database, and run Doctor." },
        { label: "Environment Setup", href: "/docs/environment-setup", description: "Configure the database, embedder, cache, and queue." },
        { label: "CLI migrate", href: "/docs/cli/migrate", description: "Apply MemoGrafter-owned database infrastructure." },
        { label: "CLI doctor", href: "/docs/cli/doctor", description: "Verify the installed schema and database readiness." },
      ],
    },
{
  "title": "Current additive schema",
  "body": [
    "Migrations 007–011 introduce mg_ingestion_runs, canonical memory identity and mg_memory_evidence, structured quality, mg_episodes with stable-topic aggregation, and mg_topic_clusters with session-scoped membership. Run the normal migration before the matching runtime.",
    "Quality migration preserves legacy confidence for audit while assigning unknown quality dimensions neutral defaults. Existing embeddings remain intact. Cluster migration requires PostgreSQL 15 or newer and leaves existing topics unassigned."
  ],
  "links": [
    {
      "label": "Quality migration",
      "href": "/docs/guides/memory-quality-migration"
    },
    {
      "label": "Topic domains",
      "href": "/docs/guides/topic-domains"
    }
  ]
}
]),

  advanced("long-running-agents", "Long-running agents", "Keep an agent useful through extended work, restarts, and large histories without replaying every turn.", [
    { title: "Design the memory boundary", body: ["Use an application-owned stable job or conversation identifier with the lower-level `MemoGrafter` API when work must be reopened across process lifetimes. `MemoGrafterAgent` owns a generated session and is best reused while that active agent instance lives."] },
    { title: "Checkpoint durable knowledge", bullets: ["Ingest completed decisions, results, and meaningful checkpoints rather than transient progress noise.", "Attach source and project tags so later recall can recover the right scope.", "Keep raw operational state in the application’s job store; MemoGrafter is memory infrastructure, not a scheduler."] },
    { title: "Recall before planning", code: [{ label: "planning-cycle.ts", language: "ts", code: `const memory = await memo.graftByRelevance(sessionId, nextTask, {
  topK: 5,
  minSimilarity: 0.55,
  hopDepth: 1,
});
const plan = await llm.complete(
  [{ role: "user", content: nextTask }],
  memory.systemPrompt,
);` }] },
    { title: "Control growth", bullets: ["Bound retrieved facts and prompt context with limits and token budgets.", "Use recent raw history for immediate continuity and graph memory for older relevant context.", "Review extraction quality before increasing retrieval breadth.", "Run crawler maintenance and reviewed lifecycle actions outside the response-critical path."] },
    { title: "Queue and cache", body: ["Queue mode can move extraction off the foreground path. Recall caching helps repeated queries over stable memory, but neither feature replaces job state, retries, monitoring, or authorization in the host application."], links: [{ label: "Queued Ingestion", href: "/docs/advanced/queued-ingestion", description: "Understand worker timing and visibility." }, { label: "Retrieval Tuning", href: "/docs/advanced/retrieval-tuning", description: "Bound relevance and prompt size." }] },
    { title: "Operational checklist", bullets: ["Use globally unique session identifiers.", "Make worker shutdown call `close()`.", "Measure invoke latency, ingestion lag, queue failures, prompt size, and empty recall rate.", "Do not create a new `MemoGrafterAgent` on every planning cycle.", "Keep tenant authorization outside MemoGrafter."] },
  ]),

  advanced("conflict-detection-versioning", "Conflict detection & versioning", "Understand how supported crawler maintenance distinguishes competing facts, explicit updates, supersession, and decay.", [
    { title: "Memory quality model", body: ["`MemoGrafterCrawler` runs deterministic, non-destructive passes over active memory. It annotates rows and creates edges; it does not delete graph nodes or rewrite historical topic summaries."] },
    { title: "Conflict versus update", bullets: ["A conflict contains competing normalized values for the same subject and predicate without an explicit update cue.", "A version update requires language such as “actually,” “now,” “changed to,” or “instead” on the newest value.", "Plain disagreement keeps both facts active and marks conflict; recency alone does not make one fact current.", "Broad topic memories are conservatively filtered to reduce false-positive conflict groups."] },
    { title: "Graph representation", bullets: ["Conflicting facts receive `hasConflict: true` and an idempotent `conflicts` memory edge.", "An older replaced fact receives `supersededBy` pointing to the newer fact.", "The update edge direction is `newer_memory --updates--> older_memory`.", "Decay evaluates persistence and stability-adjusted recency. It defaults to observation; `mode: \"enforce\"` enables retirement without changing quality."] },
    { title: "Run supported maintenance", code: [{ label: "crawler.ts", language: "ts", code: `const memo = new MemoGrafter(config);
await memo.initialize();

const crawler = new MemoGrafterCrawler({
  store: memo.store,
  intervalMs: 60_000,
});
const report = await crawler.runOnce();
console.log(report);
crawler.start();
// During shutdown:
crawler.stop();
await memo.close();` }] },
    { title: "Historical summaries", body: ["Episode summaries preserve the original bounded event; stable topics aggregate their episodes. When active memory supersedes a detail in an older summary, graft prompt assembly adds deterministic maintenance notes and active facts so the downstream model knows what to prefer."] },
    { title: "Lifecycle interaction", bullets: ["Forgotten memories and memories attached to suppressed topics are skipped.", "Already superseded or decayed rows are not treated as active candidates.", "Maintenance annotations remain visible in snapshots and history.", "Existing false-positive edges are not automatically deleted by later crawler runs."] },
    { title: "Related documentation", links: [{ label: "MemoGrafterCrawler", href: "/docs/api-reference/maintenance/memo-grafter-crawler", description: "Configure the supported maintenance orchestrator." }, { label: "Inspecting & Reviewing Memory", href: "/docs/guides/inspecting-reviewing-memory", description: "Review status, history, and memory edges." }, { label: "Pruning Memory Safely", href: "/docs/guides/pruning", description: "Choose an application lifecycle policy." }] },
{
  "title": "Ingestion integrity and observation mode",
  "body": [
    "Canonical conflict and supersession decisions now occur during ingestion commit together with immutable evidence. Crawler maintenance remains available for lifecycle passes. Decay observes by default, never overwrites quality, and requires explicit enforce mode to retire memories. Stable topic summaries aggregate episodes; the bounded episode and immutable evidence preserve historical context."
  ]
}
]),

  advanced("retrieval-tuning", "Retrieval tuning", "Tune semantic recall using representative queries, lifecycle-aware inspection, and bounded prompt budgets.", [
{
  "title": "Tune selection rather than score weights",
  "body": [
    "Use representative queries and inspect selected facts, topics, episode history, and downstream answers. Semantic similarity determines relevance; evidence quality only breaks equal-relevance ties. The obsolete scoring configuration must be removed."
  ]
},
{
  "title": "Current controls",
  "body": [
    "candidateLimit defaults to 40 and limit to 10. selection.maxTopics defaults to limit, relativeScoreFloor to 0.75, and scoreGapThreshold to 0.15. minSimilarity is deprecated for recall; semantic graft seed selection has its own options."
  ],
  "code": [
    {
      "label": "retrieval.ts",
      "language": "ts",
      "code": `const result = await memo.context({
  sessionId: "research-42", query: "What did we decide?",
  candidateLimit: 40, limit: 10, tokenBudget: 1200,
  selection: { maxTopics: 5, relativeScoreFloor: 0.75, scoreGapThreshold: 0.15 },
  episodeCandidateLimit: 40, episodeLimit: 3, episodeTokenBudget: 300,
});
console.log(result.selection, result.topicMatches, result.episodes);`
    }
  ]
},
{
  "title": "Contextualize short follow-ups",
  "body": [
    "Supply contextualization.recentMessages when a query such as “what about that deadline?” needs conversation context. Defaults bound history to eight messages and approximately 600 tokens. Built-in invocation supplies recent history; direct recall remains raw unless history is supplied. Inspect query metadata for applied, fallback, disabled, or not-needed status."
  ]
},
{
  "title": "Evaluate the right boundary",
  "body": [
    "Increase candidates before increasing prompt size. Inspect lifecycle and scope when a known fact is missing. Pinned context reserves a separate budget; clusters cannot boost retrieval. Measure response quality and selection diagnostics rather than interpreting quality dimensions as query relevance."
  ],
  "links": [
    {
      "label": "RetrieverConfig",
      "href": "/docs/api-reference/types/retriever-config"
    },
    {
      "label": "Quality migration",
      "href": "/docs/guides/memory-quality-migration"
    }
  ]
}
]),

  advanced("graph-expansion-topic-reentry", "Graph expansion & topic re-entry", "Control how semantic topic seeds expand through the graph and how returned subjects connect to earlier conversation topics.", [
    { title: "Topic graph roles", bullets: ["Temporal edges link adjacent topics.", "Semantic edges connect similar topic nodes.", "Reentry edges connect a later return to an earlier related subject.", "Grafted edges preserve relationships to copied source topics."] },
    { title: "Semantic seed selection", body: ["`graftByRelevance()` embeds the query and selects similar topic nodes. Those seed nodes are then passed to the same graft assembly path used for explicit topic IDs."] },
    { title: "Expansion controls", code: [{ label: "graph-expansion.ts", language: "ts", code: `const context = await agent.graftByRelevance("database reliability", {
  topK: 4,
  minSimilarity: 0.6,
  hopDepth: 1,
  expansionStrategy: "graph",
});` }], bullets: ["`topK` limits semantic seed topics.", "`minSimilarity` filters weak topic matches.", "`hopDepth` controls neighbour traversal distance.", "`expansionStrategy: none` formats only seed topics.", "`expansionStrategy: graph` includes reachable neighbours within the hop depth."] },
    { title: "Topic re-entry", diagram: "reentry-flow", body: ["A conversation may discuss databases, switch to authentication, and later return to connection pooling. Reentry detection links the later database topic back to the earlier one instead of merging or rewriting either historical segment."] },
    { title: "Reentry configuration", bullets: ["`reentryDetection` enables or disables reentry linking and defaults to enabled.", "`reentryThreshold` controls the required embedding similarity and defaults to 0.85.", "Reentry can connect new nodes to durable earlier nodes or to earlier segments in the same ingestion run."] },
    { title: "Tradeoffs", bullets: ["Higher hop depth can recover useful context but increase distraction and prompt size.", "Seed-only expansion is easier to reason about for user-selected topics.", "Semantic similarity does not imply authorization; scope the source graph first.", "Evaluate graph expansion using downstream answers, not only visually plausible neighbours."] },
    { title: "Related documentation", links: [{ label: "Grafting Memory", href: "/docs/guides/grafting-memory", description: "Apply graph expansion in a transfer workflow." }, { label: "graftByRelevance()", href: "/docs/api-reference/memo-grafter-agent/graft-by-relevance", description: "Review query and expansion options." }, { label: "Graph Edges", href: "/docs/concepts/graph-edges", description: "Understand the graph relationship types." }] },
  ]),

  advanced("queued-ingestion", "Queued ingestion", "Move graph construction behind BullMQ and Redis while preserving correct visibility, retries, and shutdown behavior.", [
{
  "title": "Durable jobs and compatibility paths",
  "body": [
    "Queue mode uses BullMQ and explicitly configured Redis. Initialized durable completed-exchange jobs carry stable run identity and range, with messages loaded from PostgreSQL. Compatibility message/text jobs remain for other ingestion boundaries and stores."
  ]
},
{
  "title": "Acceptance and visibility",
  "body": [
    "A queued analyzeDetailed receipt means messages were durably accepted; graphProcessed remains false until required graph work commits. Awaiting an agent local pending-ingest chain covers submission in queue mode, not worker completion."
  ],
  "diagram": "durable-ingestion-flow"
},
{
  "title": "Retry and repair",
  "body": [
    "Reuse the original idempotency key for an exchange. Inspect getIngestionRun for status, attempt, lease, and safe error metadata. reconcileSession and reconcilePendingIngestion default to inspection; select queue-accepted, recover-expired-lease, or requeue-retryable only when the report justifies it."
  ]
},
{
  "title": "Operations",
  "body": [
    "Configured queue connectivity is required; cache failures are a separate optional degradation. Monitor job age, attempts, leases, failures, provider latency, and durable run status. Close local resources deliberately and inspect drain failures; local shutdown does not establish remote worker completion."
  ],
  "links": [
    {
      "label": "Durable ingestion guide",
      "href": "/docs/guides/durable-ingestion"
    },
    {
      "label": "Errors & readiness",
      "href": "/docs/guides/errors-and-readiness"
    }
  ]
}
]),

  advanced("production-deployment", "Production deployment", "Deploy MemoGrafter as server-side memory infrastructure with deliberate migrations, isolation, workers, shutdown, and observability.", [
    { title: "Deployment boundary", body: ["MemoGrafter is server-only and experimental. Keep database credentials, provider keys, memory authorization, and lifecycle actions behind application-controlled server boundaries."] },
    { title: "Prepare the database", bullets: ["Run `memo-grafter init` during project setup.", "Run `memo-grafter migrate` as an intentional deployment step, not on every request or application startup.", "Provide PostgreSQL with `pgvector` and `pgcrypto` support.", "Use connection pooling appropriate for application and worker concurrency.", "Back up and monitor MemoGrafter-owned `mg_*` tables according to retention policy."] },
    { title: "Process topology", bullets: ["Run web or API processes for foreground recall and response generation.", "Run BullMQ workers separately when queue mode is enabled.", "Choose one deliberate owner for scheduled crawler maintenance in multi-instance deployments.", "Keep Studio local to trusted development environments."] },
    { title: "Isolation and privacy", bullets: ["Use globally unique application-owned session identifiers where the lower-level API is used.", "Authorize users, tenants, tags, and source/destination sessions before memory reads or transfer.", "Treat tags as filters, not access controls.", "Define soft-forget, hard-delete, backup, log, and export policies together.", "Avoid logging raw private memory unless required and protected."] },
    { title: "Graceful shutdown", code: [{ label: "shutdown.ts", language: "ts", code: `async function shutdown() {
  crawler?.stop();
  await fleet?.close();
  await agent?.close();
  await memo?.close();
}
process.once("SIGTERM", shutdown);
process.once("SIGINT", shutdown);` }], body: ["Only close resources owned by the current component; avoid closing the same shared core through several wrappers."] },
    { title: "Observability", bullets: ["Foreground invoke latency and first-token time.", "Recall latency, empty-result rate, selected fact count, and prompt size.", "Ingestion lag, queue depth, failed jobs, and retry count.", "Provider request latency, rate limits, and usage.", "Database pool saturation, vector-search latency, and migration status.", "Lifecycle actions and cross-session transfer audit events."] },
    { title: "Readiness checklist", bullets: ["Evaluate retrieval and transfer behavior on representative private and adversarial examples.", "Test provider, Redis, and database failure paths.", "Verify lifecycle cache invalidation.", "Test shutdown with pending ingestion.", "Confirm Studio is not publicly exposed.", "Document the installed experimental version and upgrade procedure."] },
    { title: "Related documentation", links: [{ label: "CLI migrations", href: "/docs/cli/migrate", description: "Prepare MemoGrafter-owned database infrastructure." }, { label: "Queued Ingestion", href: "/docs/advanced/queued-ingestion", description: "Operate background graph construction." }, { label: "Performance", href: "/docs/advanced/performance", description: "Measure latency, prompts, and throughput." }, { label: "Forgetting & Privacy", href: "/docs/guides/forgetting-privacy", description: "Design lifecycle and retention workflows." }] },
  ]),
];
