import type { DocPage, DocSection } from "./types";

function page(slug: string, title: string, description: string, sections: DocSection[]): DocPage {
  return { slug, title, description, eyebrow: slug.startsWith("concepts/") ? "Core Concepts" : slug.startsWith("api-reference/") ? "API Reference" : "Guides", sections };
}
const link = (label: string, slug: string) => ({ label, href: `/docs/${slug}` });
const code = (label: string, content: string) => [{ label, language: "ts", code: content }];

export const memoryPages: DocPage[] = [
  page("concepts/episodes", "Stable topics & episodes", "Keep recurring subjects together while preserving each event's bounded history.", [
    { title: "Memory hierarchy", diagram: "memory-hierarchy", body: ["A session contains stable topics, optionally organized into topic clusters. Each stable topic contains episodes, and atomic memories retain evidence from their originating exchanges. Clusters are optional navigation metadata; episodes and facts always reference the stable topic."] },
    { title: "A topic can span several episodes", body: ["A conversation about a Japan trip can return to flights after discussing work. Each processed segment produces an episode with its own summary, intent, outcome, open question, source range, tags, and assignment provenance. Topic assignment can reuse an active stable topic instead of creating another topic for every segment.", "The default episode-to-topic reuse threshold is 0.82, with at most eight candidate topics. Configure drift.topicAssignment.reuseThreshold and candidateLimit when evaluating a different policy. Reuse updates the topic's aggregate summary, activity, episode count, revision, and normalized embedding centroid; the episode preserves the bounded event."] },
    { title: "Episode history versus durable facts", body: ["Episodes explain what happened during a bounded exchange. Atomic memories represent durable user-supported state. An assistant's proposed itinerary can be part of episode context without becoming a confirmed user preference.", "Retrieval searches memory, topic, and episode vectors. Episode history has a separate prompt block and budget. Defaults are 40 episode candidates, three returned episodes, and approximately 300 episode tokens."], code: code("episode-recall.ts", `const result = await memo.context({\n  sessionId: "travel-42", query: "What did we decide about flights?",\n  episodeCandidateLimit: 40, episodeLimit: 3, episodeTokenBudget: 300,\n});\nconsole.log(result.episodes);`) },
    { title: "Inspect and migrate", body: ["Run the normal migration before upgrading the runtime. Migration 010 adds episodes and stable-topic support. GraphSnapshot.episodes exposes episode history when the store supports it."], links: [link("Topic domains", "guides/topic-domains"), link("Retrieval tuning", "advanced/retrieval-tuning")] },
  ]),
  page("concepts/canonical-memory", "Canonical memories & evidence", "Reconcile repeated observations without duplicating durable facts or losing their sources.", [
    { title: "Validate ownership first", body: ["Conversation memories must be supported by user-authored or user-confirmed state. Assistant suggestions, questions, generated explanations, and acknowledgements do not become user facts unless a user adopts them. Document ingestion uses document ownership.", "Before embedding, provenance validation checks the asserting speaker and one-based extraction message references, then converts them to absolute originating-session indexes. New memories retain speaker, originating session, supporting indexes, and extraction method. Legacy rows can have missing provenance."] },
    { title: "Reconcile inside the commit", body: ["Canonical identity lets equivalent observations reinforce an existing memory. The PostgreSQL commit records immutable evidence, canonical decisions, required lifecycle edges, and cursor advancement atomically under the session lock. Repeated evidence does not repeatedly increment reinforcement counts.", "A repeated preference should reinforce the existing fact. An explicit correction can supersede an older fact. Incompatible claims without sufficient replacement evidence remain conflicts; recency or a quality score alone does not establish which claim is true."] },
    { title: "Preserve quality and history", body: ["Reinforcement keeps the stronger explicitness/sourceReliability pair together. It preserves stability and salience. Candidate lookup uses canonical fact keys with a fallback for legacy rows; active legacy candidates are canonicalized lazily.", "Memory history and diff preserve structural changes and quality metadata. Graft and copy paths preserve supporting provenance rather than treating copied observations as newly asserted user claims."], code: code("history.ts", `const history = await agent.getMemoryHistory("user", "preferred_editor");\nconsole.log(history);\nconst diff = await agent.getMemoryDiff(previousMemoryId, currentMemoryId);`) },
    { title: "Storage and migration", body: ["Migration 008 adds canonical identity, reinforcement columns, canonical lookup indexes, and mg_memory_evidence. Run npx memo-grafter migrate before starting the matching runtime. Existing rows remain readable."], links: [link("Memory quality", "concepts/memory-quality"), link("Lifecycle and versioning", "advanced/conflict-detection-versioning")] },
  ]),
  page("concepts/memory-quality", "Memory quality", "Assess evidence, durability, and usefulness with four independent dimensions.", [
    { title: "Four dimensions", table: { headers: ["Dimension", "What it measures", "Example"], rows: [
      ["explicitness", "How directly the evidence supports the claim", "A clearly confirmed temporary task can score highly."],
      ["sourceReliability", "Trustworthiness of the source for this claim", "Explicit wording does not prove a document is correct."],
      ["stability", "How long the claim is expected to remain valid", "Tomorrow's task is less stable than a lasting preference."],
      ["salience", "Usefulness beyond the originating exchange", "A temporary deadline can still be important."],
    ] }, body: ["Scores are independent assessments between zero and one. They are not calibrated probabilities, and none represents current-query relevance."] },
    { title: "Unknown quality", body: ["Finite values are clamped to [0, 1]. Missing fields, strings, booleans, null, NaN, and infinities default independently to 0.5. qualityDefaulted records unknown dimensions; qualityOrigin identifies extracted, provided, or legacy assessments. Unknown does not mean strong evidence."], code: code("quality.ts", `import { normalizeMemoryQuality, computePersistenceScore } from "memo-grafter";\nconst quality = normalizeMemoryQuality({\n  explicitness: 0.95, sourceReliability: 0.9, stability: 0.2, salience: 0.9,\n});\nconst persistence = computePersistenceScore(quality);`) },
    { title: "Admission, retrieval, and maintenance", bullets: ["Admission follows provenance validation and runs before memory embedding. It uses explicitness and reliability thresholds, provisionally 0.3 each.", "Observation is the default. Enforce mode skips candidates below either evidence threshold; defaulted dimensions cannot trigger rejection. Low stability alone does not reject a temporary task.", "Retrieval ranks by semantic similarity. Evidence quality only breaks equal-relevance ties; stability, salience, and persistence do not boost relevance.", "Version-1 persistence is (explicitness + sourceReliability + 2 × stability + 2 × salience) / 6. Decay combines it with stability-adjusted recency and defaults to observation."] },
    { title: "Evaluate before enforcing", body: ["Inspect MEMORY_QUALITY_DEFAULTED and MEMORY_QUALITY_ADMISSION diagnostics on representative application data. Bundled fixtures and example thresholds are starting points, not a production accuracy guarantee."], links: [link("Quality migration guide", "guides/memory-quality-migration"), link("Canonical memory", "concepts/canonical-memory")] },
  ]),
  page("guides/existing-chatbot", "Integrate an existing chatbot", "Use MemoGrafter around the model call your application already owns.", [
    { title: "Read before generation, write after completion", diagram: "external-chat-flow", body: ["Use an application-owned session identifier. context() builds fresh prompt-ready memory. Your application generates the answer, then analyze() or analyzeDetailed() records the completed exchange. Do not send the same exchange through invoke() as well."] },
    { title: "Complete integration", code: code("existing-chatbot.ts", `import "dotenv/config";\nimport { MemoGrafter, OpenAILLMAdapter, OpenAIEmbedAdapter } from "memo-grafter";\n\nconst llm = new OpenAILLMAdapter("gpt-4o-mini");\nconst memo = await MemoGrafter.create({\n  db: { connectionString: process.env.DATABASE_URL! },\n  llm, embedder: new OpenAIEmbedAdapter("text-embedding-3-small"),\n});\n\ntry {\n  const sessionId = "support-42";\n  const userMessage = "I prefer email updates for my order.";\n  const context = await memo.context({ sessionId, query: userMessage });\n  const assistantMessage = await llm.complete(\n    [{ role: "user", content: userMessage }],\n    ["You are a support assistant.", context.systemPrompt].filter(Boolean).join("\\n\\n"),\n  );\n  const receipt = await memo.analyzeDetailed({\n    sessionId, userMessage, assistantMessage,\n    // Persist an application exchange ID and reuse it if this write is retried.\n    idempotencyKey: "support-42:exchange-1",\n  });\n  console.log(assistantMessage, receipt);\n} finally {\n  await memo.close({ drain: true, timeoutMs: 10_000 });\n}`) },
    { title: "Completion and fresh reads", body: ["context() bypasses configured recall caching and does not generate the assistant answer. Optional query contextualization can call the LLM to rewrite an ambiguous query. Supply bounded recent messages when needed.", "analyze() returns processed topics inline or [] after queue submission. analyzeDetailed() requires durable capabilities and exposes whether messages are accepted and whether graph processing has completed. A queued receipt cannot guarantee immediate recall."] },
    { title: "Streaming integration", body: ["Retrieve before opening the provider stream. Collect the completed assistant response and ingest it once after the stream completes. Decide explicitly how your application handles interrupted streams rather than storing partial output as a completed exchange."], links: [link("Durable ingestion", "guides/durable-ingestion"), link("Streaming responses", "guides/streaming-responses"), link("context()", "api-reference/memo-grafter/context")] },
  ]),
  page("guides/durable-ingestion", "Durable ingestion & recovery", "Track acceptance, processing, retries, and recovery through durable run identities.", [
    { title: "Acceptance is a separate boundary", diagram: "durable-ingestion-flow", body: ["On the initialized built-in PostgreSQL path, completed exchanges are atomically accepted into the message buffer with an mg_ingestion_runs record. Preparation invokes providers and validates graph objects without graph writes. Commit locks the session and run, checks the expected cursor, and atomically persists required graph state, evidence, cursor advancement, and completion.", "Durable queue jobs carry the stable run identity and range; workers reload accepted messages from PostgreSQL. Compatibility message/text queue paths remain for other ingestion APIs and custom stores. Best-effort semantic edges, telemetry, or clustering can produce warnings without undoing required memory."] },
    { title: "Accept once, inspect later", code: code("durable-ingestion.ts", `const receipt = await memo.analyzeDetailed({\n  sessionId: "support-42", userMessage, assistantMessage,\n  idempotencyKey: "support-42:exchange-17",\n}, { timeoutMs: 30_000 });\n\nif (!receipt.graphProcessed) {\n  const run = await memo.getIngestionRun(receipt.ingestionRunId);\n  console.log(run?.status, run?.attemptCount, run?.lastErrorCode);\n  // Recheck from your job monitor when work progresses; avoid fixed sleeps.\n}`), body: ["Persist the exchange key in application state and reuse it on retries. Receipt status is processed or queued; messagesPersisted, graphProcessed, messageRange, and ingestionRunId explain the durable boundary."] },
    { title: "Run states", bullets: ["accepted: durable messages and a run exist.", "queued / running / retry_pending: processing has not reached terminal success; inspect lease and attempt metadata.", "completed / completed_with_warnings: required graph work has committed.", "failed / cancelled / abandoned: inspect safe error metadata and retryability before recovery."] },
    { title: "Inspect before repair", code: code("reconciliation.ts", `const report = await memo.reconcileSession("support-42");\nconsole.log(report.issues);\n\n// Select only the recovery action justified by the report.\nawait memo.reconcileSession("support-42", {\n  mode: "repair", repairs: ["queue-accepted"],\n});`), body: ["Inspection is read-only by default. It detects accepted work that never started, expired leases, retryable failures, cursor/buffer mismatches, orphan graph rows, completed runs behind the cursor, and duplicate ranges.", "Repair supports only queue-accepted, recover-expired-lease, and requeue-retryable. reconcilePendingIngestion applies the same contract across sessions. Doctor --ingestion and Studio inspect only."] },
    { title: "Cancellation and shutdown", body: ["A signal or timeout can stop a call before acceptance. After acceptance, errors retain safe state showing durable messages; cancellation does not erase them. Keep the original exchange key for retries.", "Use close({ drain: true, timeoutMs: 10_000 }) for bounded draining. MemoGrafterShutdownError exposes failures, pendingRunCount, and jobsMayBeActive. Local shutdown is not a guarantee that remote queue workers have finished."], links: [link("Error handling", "api-reference/error-handling"), link("Queued ingestion", "advanced/queued-ingestion")] },
  ]),
  page("guides/memory-quality-migration", "Upgrade to structured memory quality", "Replace confidence-based contracts and migrate existing memory without re-embedding it.", [
    { title: "Update application code", bullets: ["Replace memory.confidence with memory.quality and read the four dimensions independently.", "Remove the obsolete retrieval scoring configuration, including scoring.confidenceWeight and similarityWeight. Similarity determines relevance; quality only breaks ties.", "Custom stores must replace updateMemoryNodeConfidence with updateMemoryNodeQuality(id, quality).",
      "Remove updateConfidence from decay options. Decay does not overwrite quality and defaults to observation; enable mode: enforce only after evaluation."], code: code("quality-admission.ts", `await memo.ingestText("Deploy the billing patch tomorrow.", "project-42", {\n  source: "release-plan",\n  sourceReliability: 0.8,\n  qualityPolicy: {\n    mode: "observe", minExplicitness: 0.3, minSourceReliability: 0.3,\n  },\n});`) },
    { title: "Run the normal migration", code: [{ label: "terminal", language: "bash", code: "npx memo-grafter init\nnpx memo-grafter migrate\nnpx memo-grafter doctor" }], body: ["Migration 009 adds constrained quality columns and metadata to memories and evidence. Existing confidence values remain only for audit/rollback; fresh databases have no confidence column. Legacy dimensions are unknown and receive neutral defaults, not fabricated assessments derived from old confidence.", "Existing embeddings and evidence remain intact. Re-extraction from original evidence is a separate opt-in application workflow. Migrations 007–011 also cover durable runs, canonical evidence, episodes, and topic clusters; use the package migration command to apply the complete schema."] },
    { title: "Observe before enforcing", body: ["qualityPolicy defaults to observe. Enforce mode rejects candidates below explicitness or sourceReliability thresholds after provenance checks and before embedding. Defaulted dimensions cannot cause rejection; low stability and salience do not reject temporary tasks. A finite caller sourceReliability overrides the extracted reliability.", "Use diagnostics.onWarning to review MEMORY_QUALITY_DEFAULTED and MEMORY_QUALITY_ADMISSION counts. The live memory-quality manual test retains its session in Studio and writes Markdown/JSON reports with snapshots, provenance, and raw extraction output for semantic review."], links: [link("Memory quality", "concepts/memory-quality"), link("Testing & pull requests", "contributing/testing-and-pull-requests")] },
  ]),
  page("guides/topic-domains", "Organize topics into domains", "Enable optional session-owned clusters without changing retrieval behavior.", [
    { title: "What clusters do", body: ["A Travel domain can organize Japan Trip, Visa Planning, and Flights. Stable topics belong to zero or one cluster; episodes and memories still reference their stable topic. Membership is separate from graph edges and has no effect on candidates, ranking, traversal, prompts, or token budgets."] },
    { title: "Enable classification", code: code("mg.config.ts — configuration fragment", `clustering: {\n  enabled: true, // Disabled by default.\n  candidateLimit: 8,\n  minConfidence: 0.9,\n  timeoutMs: 10_000,\n  retryAfterMs: 86_400_000,\n  maxTopicsPerRun: 8,\n},`), body: ["Migrate first; migration 011 adds cluster storage and requires PostgreSQL 15 or newer. The supplied Docker example uses PostgreSQL 16.", "Classification runs after ingestion commits. It embeds a separate domain description, verifies bounded catalog candidates, and prioritizes canonical labels and verified aliases. Ambiguity leaves a topic unassigned. Revisions, cooldowns, and per-run limits bound repeated work; existing assignments remain stable. Provider calls add post-commit latency, and failures emit diagnostics without undoing memory."] },
    { title: "Backfill existing topics", code: code("backfill.ts", `let afterId: string | undefined;\ndo {\n  const page = await memo.backfillTopicClusters("travel-42", { afterId, limit: 8 });\n  console.log(page.warnings);\n  afterId = page.nextCursor ?? undefined;\n} while (afterId);\nconst clusters = await memo.getTopicClusters("travel-42");`), body: ["The cursor resumes a bounded scan. Start another full pass later to revisit eligible failures after cooldown. getTopicClusters returns domain descriptions without embedding vectors."] },
    { title: "Inspect and maintain", bullets: ["Studio's Clusters view groups topics by domain and includes Unclustered. Topic details, snapshots, table exports, and invocation previews expose domain metadata.", "context() hydrates current clusterMetadata after selection, including episode-only topic references. Disabling classification preserves existing metadata.", "Deleting a cluster clears membership without deleting topics. Suppression preserves membership while excluding the topic from active retrieval metadata. Clearing a session removes its domains.", "Grafted topics never retain a source-session cluster ID. SDK absorption can classify destination copies; Studio/store-only copies can use backfill.", "Custom stores may omit cluster capabilities. Enabling unsupported classification emits a non-fatal warning."], links: [link("Stable topics & episodes", "concepts/episodes"), link("Graph Store", "advanced/graph-store")] },
  ]),
  page("guides/topic-pinning", "Pin required context", "Keep selected active topics in invocation context even when the query is unrelated.", [
    { title: "Pin a topic", code: code("pins.ts", `await memo.pinTopic("support-42", topicId);\nconst topics = await memo.getPinnedTopics("support-42");\nconst pinned = await memo.getPinnedContext("support-42");\nconsole.log(topics, pinned.truncated, pinned.tokenCount);\n\n// Later, remove the requirement while preserving the topic.\nawait memo.unpinTopic("support-42", topicId);`), body: ["Agent equivalents use the current session: agent.pinTopic(topicId), unpinTopic(topicId), and getPinnedTopics(). Core methods accept a session ID. Pin and unpin return whether a row changed."] },
    { title: "Prompt composition", body: ["context() and invocation planning prepend active pinned context in pin order and deduplicate recalled topic blocks. Pinned context uses the configured inject.tokenBudget separately from retrieved facts and episode history.", "getPinnedContext returns prompt, topics, active memories, token count, budget, and truncated. RetrievalResult exposes pinnedNodes, pinnedContextTruncated, and pinnedTokenBudget. Inspect truncation when a large required topic does not fit."] },
    { title: "Lifecycle semantics", body: ["Suppressed topics cannot contribute active pinned context. Forgotten, decayed, and superseded memories remain excluded. A pin does not alter quality, conflict state, maintenance eligibility, or ownership. Unpinning preserves memory for normal retrieval."], links: [link("Recall & memory injection", "guides/recall-memory-injection"), link("Lifecycle actions", "studio/lifecycle-actions")] },
  ]),
  page("guides/errors-and-readiness", "Handle errors & readiness", "Observe degraded success and recover failed operations using structured state.", [
    { title: "Verify configuration", code: code("readiness.ts", `const memo = await MemoGrafter.create(config, {\n  diagnostics: {\n    onWarning(warning) {\n      console.warn({ code: warning.code, operation: warning.operation });\n    },\n  },\n});\nconsole.log(await memo.checkReadiness());`), body: ["Factory readiness checks adapter shape, installed optional provider SDKs, and required environment variables without a provider request. Initialize against an already migrated database. Doctor can explain missing initialization, required schema, database, and configured Redis failures."] },
    { title: "Use operation options", code: code("deadline.ts", `const controller = new AbortController();\nconst result = await memo.context(\n  { sessionId: "support-42", query: "current commitments" },\n  { signal: controller.signal, timeoutMs: 10_000 },\n);\nif (result.degraded) console.warn(result.warnings);`), body: ["Supported long-running boundaries accept signal and timeoutMs. Explicit aborts use OPERATION_ABORTED; framework deadlines use retryable OPERATION_TIMEOUT. Required provider, embedding, and database work still fails the affected operation. Inspect MemoGrafterError.code, operation, retryable, and safe context."] },
    { title: "Classify the failure", table: { headers: ["Boundary", "Required failure", "Best-effort behavior"], rows: [
      ["Retrieval", "Database or embedder", "Cache failures can return degraded context with warnings."],
      ["Ingestion", "Required provider or database work", "Enrichment can complete with warnings; accepted messages persist."],
      ["Maintenance", "Required pass work", "Configured reports can capture individual pass failures."],
      ["Doctor", "Invalid configuration, database, configured queue", "Optional cache failures warn."],
      ["Studio", "API or storage", "Unavailable health metadata can be reported separately."],
    ] } },
    { title: "Recover using durable state", body: ["Use toJSON() for allowlisted operational metadata. Ingestion errors can report persisted messages, range, cursor advancement, and retry safety. Reuse the original idempotency key; inspect runs and reconciliation reports before selecting repairs. Closing local resources does not prove completion by remote workers."], links: [link("Error reference", "api-reference/error-handling"), link("Durable ingestion & recovery", "guides/durable-ingestion")] },
  ]),
  page("api-reference/graph-store/update-memory-node-confidence", "Migrate updateMemoryNodeConfidence()", "This storage method has been replaced by updateMemoryNodeQuality().", [
    { title: "Use structured quality", body: ["Custom stores and callers must replace updateMemoryNodeConfidence(id, confidence) with updateMemoryNodeQuality(id, quality). The four dimensions cannot be reconstructed from a legacy confidence number. Preserve legacy values for audit and use unknown quality until evidence is assessed."], links: [link("updateMemoryNodeQuality()", "api-reference/graph-store/update-memory-node-quality"), link("Migration guide", "guides/memory-quality-migration")] },
  ]),
];
